# config — centralized UI constants and application defaults

from gfglock.config.defaults import (
    AppInfo,
    get_default_settings,
    ThemeDefaults,
    EncryptionDefaults,
    DecryptionDefaults,
    AlgorithmDefaults,
    LoggingDefaults,
)
from gfglock.config.ui_config import (
    get_dpi_scale,
    scale_size,
    scale_value,
    WindowSizes,
    IconSizes,
    ButtonSizes,
    Spacing,
    FontSizes,
    ComboBoxSizes,
    LabelSizes,
    ThemeColors,
    EncryptionModes,
    ChunkSizeOptions,
    FileItemSizes,
    FileItemColors,
    get_scaled_window_size,
    get_dialog_margins,
)

__all__ = [
    "AppInfo",
    "get_default_settings",
    "ThemeDefaults",
    "EncryptionDefaults",
    "DecryptionDefaults",
    "AlgorithmDefaults",
    "LoggingDefaults",
    "get_dpi_scale",
    "scale_size",
    "scale_value",
    "WindowSizes",
    "IconSizes",
    "ButtonSizes",
    "Spacing",
    "FontSizes",
    "ComboBoxSizes",
    "LabelSizes",
    "ThemeColors",
    "EncryptionModes",
    "ChunkSizeOptions",
    "FileItemSizes",
    "FileItemColors",
    "get_scaled_window_size",
    "get_dialog_margins",
]
